entries = {
  "app.title": "Nano Draw",
  "app.subtitle": "Gemini 影像夥伴",
  "app.credit": "由 Yapi 製作",
  "panel.promptTitle": "提示工作室",
  "panel.promptDescription": "撰寫你的靈感，並保存最佳提示。",
  "prompt.placeholder": "描述你想生成的畫面。",
  "panel.presetsTitle": "提示預設",
  "panel.presetsEmpty": "尚無預設，儲存喜愛的提示以便快速套用。",
  "panel.stylesTitle": "風格素材",
  "panel.stylesDescription": "上傳靈感並建立可重複使用的風格庫。",
  "panel.currentStyles": "目前輸入",
  "panel.libraryStyles": "風格庫",
  "panel.generateTitle": "生成",
  "panel.generateDescription": "將提示送給 Gemini，快速迭代。",
  "panel.resultsTitle": "結果",
  "panel.resultsDescription": "複製、下載，或轉換為新的風格參考。",
  "upload.title": "加入參考圖片",
  "upload.subtitle": "拖曳檔案或點擊選擇（最多 6 張）。",
  "loading.generating": "正在為你創作圖像...",
  "actions.savePreset": "儲存預設",
  "actions.clearPrompt": "清空",
  "actions.clearAll": "全部清除",
  "actions.resetInputs": "重設輸入",
  "actions.clearLibrary": "清空風格庫",
  "actions.generate": "開始生成",
  "actions.clearResults": "清除結果",
  "actions.save": "儲存",
  "actions.remove": "移除",
  "actions.applyPreset": "套用",
  "actions.setDefault": "設為預設",
  "actions.defaultActive": "預設",
  "actions.deletePreset": "刪除",
  "actions.saveToLibrary": "儲存",
  "actions.removeInput": "移除",
  "actions.useStyle": "使用",
  "actions.deleteStyle": "刪除",
  "actions.copy": "複製",
  "actions.download": "下載",
  "actions.styleFromResult": "當作風格",
  "settings.title": "設定",
  "settings.apiTitle": "Gemini API",
  "settings.apiKeyLabel": "API 金鑰",
  "settings.apiKeyPlaceholder": "AIza...",
  "settings.appearanceTitle": "外觀",
  "settings.theme": "主題",
  "settings.themeLight": "淺色",
  "settings.themeDark": "深色",
  "settings.layout": "版面",
  "settings.layoutPopout": "彈出視窗",
  "settings.layoutSidebar": "側邊欄",
  "settings.languageTitle": "介面語言",
  "settings.language": "選擇語言",
  "settings.languageEnglish": "英文",
  "settings.languageChinese": "繁體中文",
  "settings.aboutTitle": "關於",
  "settings.credit": "由 Yapi 設計與開發。",
  "badge.default": "預設",
  "grid.currentEmpty": "尚未選擇風格輸入。",
  "grid.libraryEmpty": "尚未儲存風格。",
  "grid.resultsEmpty": "生成結果將顯示於此。",
  "status.promptRequired": "請先輸入提示再生成。",
  "status.apiKeyMissing": "請先在設定中加入 Gemini API 金鑰。",
  "status.apiKeyEmpty": "請輸入 API 金鑰。",
  "status.inputLimit": "已達 {{max}} 張風格圖片的上限。",
  "status.readFailed": "無法讀取 {{name}}。",
  "status.styleSaved": "已儲存至風格庫。",
  "status.styleExists": "此圖片已經儲存過。",
  "status.styleRemoved": "已從風格庫移除。",
  "status.libraryCleared": "已清空風格庫。",
  "status.presetSaved": "已儲存提示預設。",
  "status.presetExists": "此提示已存在。",
  "status.presetLimit": "提示預設上限為 {{max}} 筆。",
  "status.presetApplied": "已套用提示預設。",
  "status.defaultPresetSet": "已更新預設提示。",
  "status.presetRemoved": "已刪除提示預設。",
  "status.presetsCleared": "已清除所有提示預設。",
  "status.resultsCleared": "已清除生成結果。",
  "status.promptCleared": "已清空提示內容。",
  "status.apiSaved": "已儲存 API 金鑰。",
  "status.apiRemoved": "已移除 API 金鑰。",
  "status.copySuccess": "已複製到剪貼簿。",
  "status.copyFailed": "複製失敗，請改用下載。",
  "status.noImages": "伺服器未回傳圖片。",
  "status.generatedCount": "取得 {{count}} 張圖片。",
  "status.generationFailed": "生成失敗。",
  "status.loadSettingsFailed": "無法載入儲存的設定。",
  "confirm.clearLibrary": "確定要清除所有風格嗎？",
  "confirm.clearPresets": "確定要移除所有提示預設嗎？",
  "aria.openSettings": "開啟設定",
  "aria.closeSettings": "關閉設定",
  "aria.dragModule": "拖曳以重新排序",
  "result.alt": "第 {{index}} 張生成結果",
  "label.style": "風格",
  "label.result": "結果 {{index}}",
  "file.default": "nano-draw"
}

def escape_unicode(value):
    return value.encode('unicode_escape').decode('ascii')

lines = []
for idx, (key, value) in enumerate(entries.items()):
    line = f'    "{key}": "{escape_unicode(value)}"'
    if idx < len(entries) - 1:
        line += ','
    lines.append(line)

print('\n'.join(lines))
